import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import CartProvider from "./components/Providers";
import dynamic from "next/dynamic";


const inter = Inter({ subsets: ["latin"] });

const NoSSR = dynamic(() => import('./components/ShoppingCartModal'), { ssr: false })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <CartProvider>
        <Navbar/>
        <NoSSR />
               {children}
        </CartProvider>
        </body>
    </html>
  );
}
